FROM node:21-alpine AS builder
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm ci
COPY ./backend/. .
RUN npm run build

FROM node:21-alpine as production
WORKDIR /app
RUN npm i -g pm2
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev && npm cache clean --force
COPY --from=builder /app/dist ./dist/
COPY ./backend/ecosystem.config.js .
EXPOSE 3000
ENTRYPOINT ["pm2-runtime", "start", "ecosystem.config.js"]
