FROM node:16-alpine AS builder
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm i
COPY ./backend/. .
RUN npm run build

FROM node:16-alpine as production
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm i --omit=dev
COPY --from=builder /app/dist ./dist/
CMD ["node", "./dist/main.js"]
