FROM node:16-alpine AS builder
WORKDIR /app
COPY ./backend/package*.json ./
RUN npm i
COPY ./backend/. .
RUN npm run build

FROM node:16-alpine as production
WORKDIR /app
RUN npm install -g pm2
COPY --from=builder /app/package*.json ./
RUN npm i --omit=dev
COPY --from=builder /app/dist ./dist/
COPY ./backend/ecosystem.config.js .
EXPOSE 3000
CMD ["pm2-runtime", "start", "ecosystem.config.js"]
