FROM node:16-alpine as build
WORKDIR /app
COPY ./frontend/package*.json ./
RUN npm i
COPY ./frontend/. .
RUN npm run build

FROM nginx:stable-alpine as production
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm i --omit=dev
COPY .-from=builder /app/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
